apiVersion: v1
kind: Service
metadata:
  name: flask-security-service
  labels:
    app: flask-security-app
spec:
  selector:
    app: flask-security-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000

