apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-security-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-security-app
  minReplicas: 2
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 25
  behavior:
    scaleDown:
      # once metrics fall below targets, wait at most 30s before scaling
      stabilizationWindowSeconds: 30
      policies:
        # allow killing up to 50% of pods at a time
        - type: Percent
          value: 50
          periodSeconds: 15
      selectPolicy: Max
