apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/flask-logs
